'use strict';

exports.list = [
  'Lambda.addPermission',
  'Lambda.createAlias',
  'Lambda.createEventSourceMapping',
  'Lambda.createFunction',
  'Lambda.deleteAlias',
  'Lambda.deleteEventSourceMapping',
  'Lambda.deleteFunction',
  'Lambda.deleteFunctionConcurrency',
  'Lambda.getAccountSettings',
  'Lambda.getAlias',
  'Lambda.getEventSourceMapping',
  'Lambda.getFunction',
  'Lambda.getFunctionConfiguration',
  'Lambda.getPolicy',
  'Lambda.invoke',
  'Lambda.invokeAsync',
  'Lambda.listAliases',
  'Lambda.listEventSourceMappings',
  'Lambda.listFunctions',
  'Lambda.listTags',
  'Lambda.listVersionsByFunction',
  'Lambda.publishVersion',
  'Lambda.putFunctionConcurrency',
  'Lambda.removePermission',
  'Lambda.tagResource',
  'Lambda.untagResource',
  'Lambda.updateAlias',
  'Lambda.updateEventSourceMapping',
  'Lambda.updateFunctionCode',
  'Lambda.updateFunctionConfiguration'
];
